### ISSUE TITLE
Error on make install

### ISSUE THREAD

**Issue by eracle** [nestauk/ds-cookiecutter#167]
### version information

```
pre-commit version: 2.21.0
git --version: git version 2.17.1
sys.version:
    3.8.16 (default, Jan 17 2023, 23:13:24) 
    [GCC 11.2.0]
sys.executable: /home/user/miniconda3/envs/production_lab/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node', '/home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout: (none)
stderr:
    /home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node)
    
```

```
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/main.py", line 376, in main
    return install(
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 140, in install
    install_hooks(config_file, store)
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/commands/install_uninstall.py", line 146, in install_hooks
    install_hook_envs(all_hooks(load_config(config_file), store), store)
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/languages/node.py", line 111, in install_environment
    helpers.run_setup_cmd(prefix, local_install_cmd)
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 48, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/home/user/miniconda3/envs/production_lab/lib/python3.8/site-packages/pre_commit/util.py", line 143, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node', '/home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
stdout: (none)
stderr:
    /home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/user/.cache/pre-commit/repoomaxdnzu/node_env-default/bin/node)

**Comment by sqr00t** [comment]
Heya @eracle , this cookiecutter template has been built, maintained, and is used internally by our team. We are glad that external users such as yourself took a liking to adopt it :)

The pre-commit hooks are as customisable as you have done as a hotfix, though the specific error you've faced is due to missing `GLIBC_2.28`. I'm not sure of what your linux setup looks like (including node/npm installation), but we primarily support Mac OS on Apple Silicon.

I'll close this issue if there's no further input in 21 days.
